stages:
  - build_image


.script_1: &script_init_image_var |
  export REPO_IMAGE_NAME=$CI_PROJECT_NAME
  export REPO_IMAGE_TAG=$CI_COMMIT_SHORT_SHA
  export APP_IMAGE=$REPO_SERVER/$REPO_NAMESPACE/$REPO_IMAGE_NAME:$REPO_IMAGE_TAG


build_image:
  stage: build_image
  image:
    name: cr.d.xiaomi.net/containercloud/kaniko-executor-xiaomi:release-latest
    entrypoint: [""]
  script:
    - *script_init_image_var
    - echo "{\"auths\":{\"$REPO_SERVER\":{\"username\":\"$REPO_USER\",\"password\":\"$REPO_PASS\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --destination $APP_IMAGE --validate-image
